name: Node.js CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install Dependencies
        working-directory: ./Backend-Favorites-App
        run: npm ci
      - name: Run Tests
        working-directory: ./Backend-Favorites-App
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MDB }}
