name: Node.js CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: Checkout # access repo code
        uses: actions/checkout@v4

      - name: Use Node.js # Ensures Node and npm installed in actions
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: Backend-Favorites-App/package-lock.json

      - name: Install Dependencies
        working-directory: ./Backend-Favorites-App
        run: npm ci

      - name: Run Tests
        env:
          MONGO_URI: ${{ secrets.MDB }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ATS }}
          REFRESH_TOKEN_SECRET: ${{ secrets.RTS }}
          PORT: ${{ secrets.PORT }}
        working-directory: ./Backend-Favorites-App
        run: npm test
