name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install Dependencies
        working-directory: ./Backend-Favorites-App
        run: npm ci # over npm install, faster since skips certain checks
        # - run: npm run build --if-present
      - name: Run Tests
        working-directory: ./Backend-Favorites-App
        run: npm ci
